name: CI Workflow Main
on:
  push:
    branches:
      - 'main'
  pull_request:
  workflow_call:
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #- name: Setup JDK 11
      #  uses: actions/setup-java@v3
      #  with:
      #    java-version: '11'
      #    distributtion: 'zulu'
      - name: Maven Test
        run: mvn --activate-profiles prod test
  package:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      #- name: Setup JDK 11
      #  uses: actions/setup-java@v3
      #  with:
      #    java-version: '11'
      #    distribution: 'zulu'
      - name: Maven Package
        run: mvn --activate-profiles prod -DskipTests package
